<input type="hidden" id="are_you_sure" value="{{__('alert.are_you_sure')}}">
<input type="hidden" id="delete_warning" value="{{__('alert.delete_warning')}}">
<input type="hidden" id="yes_sure" value="{{__('alert.yes_sure')}}">
<input type="hidden" id="success" value="{{__('alert.success')}}">
<input type="hidden" id="error" value="{{__('alert.error')}}">
<input type="hidden" id="internet_connected" value="{{__('alert.internet_connected')}}">
<input type="hidden" id="offline_internet" value="{{__('alert.offline_internet')}}">
<input type="hidden" id="try_again" value="{{__('alert.try_again')}}">
<input type="hidden" id="close_lang" value="{{__('general.close')}}">
<input type="hidden" id="product_sisa" value="{{__('alert.product_sisa')}}">
<input type="hidden" id="billing_empty" value="{{__('alert.billing_empty')}}">
<input type="hidden" id="due_total" value="{{__('sell.due_total')}}">
<input type="hidden" id="change_total" value="{{__('sell.change_total')}}">
<input type="hidden" id="date_lang" value="{{__('general.date')}}">
<input type="hidden" id="subtotal_lang" value="{{__('general.subtotal')}}">
<input type="hidden" id="discount_lang" value="{{__('general.discount')}}">
<input type="hidden" id="tax_lang" value="{{__('purchase.tax')}}">
<input type="hidden" id="shipping_lang" value="{{__('purchase.shipping_cost')}}">
<input type="hidden" id="other_lang" value="{{__('purchase.other_payment')}}">
<input type="hidden" id="total_lang" value="{{__('general.total')}}">
<input type="hidden" id="payment_lang" value="{{__('general.payment_total')}}">
<input type="hidden" id="method_lang" value="{{__('general.payment_method')}}">
<input type="hidden" id="hold_lang" value="{{__('pos.hold')}}">