const purchase = {
    path: "/app/purchase",
    redirect: "/app/purchase/received",
    component: () => import("../../index.vue"),
    children: [
        {
            path: "po",
            redirect: "/app/purchase/po/list",
            children: [
                {
                    name: "purchase_po",
                    path: "list",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/po/list",
                        keepAlive: true,
                        title: "Daftar Pesanan Barang",
                        parent_menu: "purchase_po",
                        icon: "fe fe-list",
                        parent: {
                            name: "purchase_po",
                            title: "Pesanan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
                {
                    name: "purchase_po_create",
                    path: "create",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/po/create",
                        keepAlive: true,
                        closeTab: true,
                        title: "Buat Pesanan Barang",
                        parent_menu: "purchase_po",
                        icon: "fe fe-plus-circle",
                        parent: {
                            name: "purchase_po",
                            title: "Pesanan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
                {
                    name: "purchase_po_update",
                    path: "update/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/po/update/:id",
                        keepAlive: false,
                        closeTab: true,
                        title: "Edit Pesanan Barang",
                        parent_menu: "purchase_po",
                        icon: "fe fe-edit",
                        parent: {
                            name: "purchase_po",
                            title: "Pesanan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
                {
                    name: "purchase_po_detail",
                    path: "detail/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/po/detail/:id",
                        keepAlive: false,
                        title: "Detail Pesanan Barang",
                        parent_menu: "purchase_po",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_po",
                            title: "Pesanan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
            ],
        },
        {
            path: "received",
            redirect: "/app/purchase/received/list",
            children: [
                {
                    name: "purchase_received",
                    path: "list",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/received/list",
                        keepAlive: true,
                        title: "Daftar Penerimaan Barang",
                        parent_menu: "purchase_received",
                        icon: "fe fe-list",
                        parent: {
                            name: "purchase_received",
                            title: "Penerimaan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
                {
                    name: "purchase_received_create",
                    path: "create",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/received/create",
                        keepAlive: true,
                        closeTab: true,
                        title: "Buat Penerimaan Barang",
                        parent_menu: "purchase_received",
                        icon: "fe fe-plus-circle",
                        parent: {
                            name: "purchase_received",
                            title: "Penerimaan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
                {
                    name: "purchase_received_update",
                    path: "update/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/received/update/:id",
                        keepAlive: false,
                        closeTab: true,
                        title: "Edit Penerimaan Barang",
                        parent_menu: "purchase_received",
                        icon: "fe fe-edit",
                        parent: {
                            name: "purchase_received",
                            title: "Penerimaan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
                {
                    name: "purchase_received_detail",
                    path: "detail/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/received/detail/:id",
                        keepAlive: false,
                        title: "Detail Penerimaan Barang",
                        parent_menu: "purchase_received",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_received",
                            title: "Penerimaan Barang",
                            icon: "fe fe-box",
                        },
                    },
                },
            ],
        },
        {
            path: "faktur",
            redirect: "/app/purchase/faktur/list",
            children: [
                {
                    name: "purchase_list",
                    path: "list",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/faktur/list",
                        keepAlive: false,
                        title: "Faktur Pembelian",
                        parent_menu: "purchase_list",
                        icon: "fe fe-list",
                        parent: {
                            name: "purchase_list",
                            title: "Faktur Pembelian",
                            icon: "fe fe-shopping-bag",
                        },
                    },
                },
                {
                    name: "purchase_create",
                    path: "create",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/faktur/create",
                        keepAlive: true,
                        closeTab: true,
                        title: "Buat Faktur Pembelian",
                        parent_menu: "purchase_list",
                        icon: "fe fe-plus-circle",
                        parent: {
                            name: "purchase_list",
                            title: "Faktur Pembelian",
                            icon: "fe fe-shopping-bag",
                        },
                    },
                },
                {
                    name: "purchase_update",
                    path: "update/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/faktur/update/:id",
                        keepAlive: false,
                        closeTab: true,
                        title: "Edit Faktur Pembelian",
                        parent_menu: "purchase_list",
                        icon: "fe fe-edit",
                        parent: {
                            name: "purchase_list",
                            title: "Faktur Pembelian",
                            icon: "fe fe-shopping-bag",
                        },
                    },
                },
                {
                    name: "purchase_detail",
                    path: "detail/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/faktur/detail/:id",
                        keepAlive: false,
                        title: "Detail Faktur Pembelian",
                        parent_menu: "purchase_list",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_list",
                            title: "Faktur Pembelian",
                            icon: "fe fe-shopping-bag",
                        },
                    },
                },
            ],
        },
        {
            path: "payment",
            redirect: "/app/purchase/payment/list",
            children: [
                {
                    name: "purchase_payment_list",
                    path: "list",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/payment/list",
                        keepAlive: false,
                        title: "Pembayaran Pembelian",
                        parent_menu: "purchase_payment_list",
                        icon: "fe fe-list",
                        parent: {
                            name: "purchase_payment_list",
                            title: "Pembayaran Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
                {
                    name: "purchase_payment_create",
                    path: "create",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/payment/create",
                        keepAlive: true,
                        closeTab: true,
                        title: "Buat Pembayaran Pembelian",
                        parent_menu: "purchase_payment_list",
                        icon: "fe fe-plus-circle",
                        parent: {
                            name: "purchase_payment_list",
                            title: "Pembayaran Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
                {
                    name: "purchase_payment_update",
                    path: "update/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/payment/update/:id",
                        keepAlive: false,
                        closeTab: true,
                        title: "Edit Pembayaran Pembelian",
                        parent_menu: "purchase_payment_list",
                        icon: "fe fe-pencil",
                        parent: {
                            name: "purchase_payment_list",
                            title: "Pembayaran Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
                {
                    name: "purchase_payment_detail",
                    path: "detail/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/payment/detail/:id",
                        keepAlive: false,
                        title: "Detail Pembayaran Pembelian",
                        parent_menu: "purchase_payment_list",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_payment_list",
                            title: "Pembayaran Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
            ],
        },
        {
            path: "return",
            redirect: "/app/purchase/return/list",
            children: [
                {
                    name: "purchase_return_list",
                    path: "list",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/return/list",
                        keepAlive: false,
                        title: "Retur Pembelian",
                        parent_menu: "purchase_return_list",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_return_list",
                            title: "Retur Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
                {
                    name: "purchase_return_create",
                    path: "create/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/return/create",
                        keepAlive: false,
                        closeTab: true,
                        title: "Retur Pembelian",
                        parent_menu: "purchase_return_list",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_return_list",
                            title: "Retur Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
                {
                    name: "purchase_return_update",
                    path: "update/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/return/update/:id",
                        keepAlive: false,
                        closeTab: true,
                        title: "Buat Retur Pembelian",
                        parent_menu: "purchase_return_list",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_return_list",
                            title: "Retur Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
                {
                    name: "purchase_return_detail",
                    path: "detail/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/return/detail/:id",
                        keepAlive: false,
                        title: "Detail Retur Pembelian",
                        parent_menu: "purchase_return_list",
                        icon: "fe fe-file-text",
                        parent: {
                            name: "purchase_return_list",
                            title: "Retur Pembelian",
                            icon: "fa fa-money",
                        },
                    },
                },
            ],
        },
        {
            path: "supplier",
            redirect: "/app/purchase/supplier/list",
            children: [
                {
                    name: "supplier",
                    path: "list",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/supplier/list",
                        title: "Pemasok",
                        parent_menu: "supplier",
                        icon: "fa fa-users",
                        parent: {
                            name: "supplier",
                            title: "Pemasok",
                            icon: "fe fe-user",
                        },
                    },
                },
                {
                    name: "supplier_create",
                    path: "create",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/supplier/create",
                        closeTab: true,
                        title: "Tambah Pemasok",
                        parent_menu: "supplier",
                        icon: "fa fa-users",
                        parent: {
                            name: "supplier",
                            title: "Pemasok",
                            icon: "fe fe-user",
                        },
                    },
                },
                {
                    name: "supplier_update",
                    path: "update/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/supplier/update/:id",
                        closeTab: true,
                        title: "Edit Pemasok",
                        parent_menu: "supplier",
                        icon: "fa fa-users",
                        parent: {
                            name: "supplier",
                            title: "Pemasok",
                            icon: "fe fe-user",
                        },
                    },
                },
                {
                    name: "supplier_due",
                    path: "supplier-due/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/supplier/purchase/supplier-due/:id",
                        title: "Hutang Pemasok",
                        parent_menu: "supplier",
                        icon: "fa fa-users",
                        parent: {
                            name: "supplier",
                            title: "Pemasok",
                            icon: "fe fe-user",
                        },
                    },
                },
                {
                    name: "supplier_saldo",
                    path: "supplier-saldo/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/supplier/purchase/supplier-saldo/:id",
                        title: "Saldo Pemasok",
                        parent_menu: "supplier",
                        icon: "fa fa-users",
                        parent: {
                            name: "supplier",
                            title: "Pemasok",
                            icon: "fe fe-user",
                        },
                    },
                },
                {
                    name: "supplier_transaction",
                    path: "supplier-history/:id",
                    component: () => import("../../index.vue"),
                    meta: {
                        url: "/panel/purchase/supplier/purchase/supplier-history/:id",
                        title: "Transaksi Pemasok",
                        parent_menu: "supplier",
                        icon: "fa fa-users",
                        parent: {
                            name: "supplier",
                            title: "Pemasok",
                            icon: "fe fe-user",
                        },
                    },
                },
            ],
        },
    ],
};

const purchaseRoutes = [purchase];

export default purchaseRoutes;
